### ISSUE TITLE
gentoo-syntax has been renamed to ebuild-mode

### ISSUE THREAD

**Issue by ulm** [emacsmirror/p.old#18]
The project was renamed. The repository is still at git://git.overlays.gentoo.org/proj/emacs-tools.git but it's the "ebuild-mode" branch now.

**Comment by tarsius** [comment]
I was rather busy maintaining magit the last few months and I am only now getting back to following such package moves.

Unfortunately I cannot find the new ebuild-mode. The url you provided doesn't work. Is this due to the outage mentioned at http://overlays.gentoo.org? The only link I could find on http://wiki.gentoo.org/wiki/Project:Emacs is to http://git.overlays.gentoo.org/gitweb/?p=proj/emacs.git;a=summary, which only contains the overlay and some backups.

**Comment by ulm** [comment]
description Gentoo-specific software related to Emacs
URL git://git.overlays.gentoo.org/proj/emacs-tools.git
    https://git.overlays.gentoo.org/gitroot/proj/emacs-tools.git
    git+ssh://git@git.overlays.gentoo.org/proj/emacs-tools.git

The ebuild-mode branch is here: http://git.overlays.gentoo.org/gitweb/?p=proj/emacs-tools.git;a=shortlog;h=refs/heads/ebuild-mode

**Comment by tarsius** [comment]
Hm, must have been confused. Anyway, ebuild-mode is now being mirrored, finally.

Sorry for the delay. I was quite busy working on magit.
