### ISSUE TITLE
cedet doesn't seem to be getting updated

### ISSUE THREAD

**Issue by dsedivec** [emacsmirror/p.old#4]
Thank you for maintaining emacsmirror!  I use it extensively.

http://cedet.bzr.sourceforge.net/bzr/cedet/code/trunk/changes shows updates, but http://github.com/emacsmirror/cedet/ shows last change seven months ago, so I hypothesize that your mirror may be broken.

**Comment by tarsius** [comment]
Unfortunately I am not able to import cedet anymore because of some bizarre bazaar bug. The cedet maintainers used to provide a git mirror of the bzr repository themselves which I in turn mirrored (bzr is no fun). They stopped providing that mirror and when I tried doing the import myself I ran into the same problem as they did.

However it appears like David Holm somehow succeeded in importing it, so you might want to use his mirror for now. I don't know whether he "cheated" somehow.

I have contacted him a week or two ago to learn more but so far he has not replied.

**Comment by tarsius** [comment]
Using new bzr support in git-1.8.\* (`git remote-bzr`) makes it possible to mirror cedet again.

Because I need to use the same importer for all bzr packages making the switch will take some time. But I will definitely switch to `git remote-bzr` (and `git-remote-hg`) and will then mirror cedet again.

**Comment by dsedivec** [comment]
Cool, thanks again!

**Comment by root42** [comment]
Any news on this problem? I really would like to have updated git access to cedet...

**Comment by tarsius** [comment]
Cedet is mirrored again. From the upstream git mirror, see http://cedet.sourceforge.net/bzr-repo.shtml.
