### ISSUE TITLE
Please don't delete repositories people may depend on

### ISSUE THREAD

**Issue by vemv** [emacsmirror/p.old#6]
Was there a good reason for deleting the cua-base mirror?

Even if there was, once published some responsability ought to be assumed imo.

That said, thanks for the work you're doing.

Victor

**Comment by tarsius** [comment]
I am sorry for the inconvenience the removal of cua-base has caused.  I generally avoid removing repositories whenever possible and reasonable.  But I increasingly move packages from the Emacsmirror to the Emacsattic unannounced and will continue to do so.

Cua-mode is a built-in package.  I used to extract the history of built-in packages from the full history of Emacs.

Recently I have removed all >400 repositories containing these individual built-in packages (removed; not moved to the attic).  That wasn't an easy decision.  I was aware this could inconvenient users and would (also for other reasons) have preferred to keep them.

I originally added these repositories because I though users would find them useful and because I though it would make things easier technically because it allowed me to treat build-in packages basically the same as third-party packages.  Until now I have got exactly zero feedback on these repositories and on the technical side it turned into a nightmare.

The history of mirrored packages was being extracted by git-subpull which I have originally written to extract packages from the Emacswiki.  While I continue to use it for the originally intended purpose it just isn't sane enough to rewrite history of large non-linear history such as found in the Emacs repository.

Any help replacing git-subpull with something sane and well tested (and with a maintainer that doesn't try to avoid remembering it's existence :-) would be highly welcome.

I did not update the repositories of built-in packages regularly as I do for other packages.  And every time I did update there was a failure rate of about 5%.  Nothing that couldn't be fixed manually but it always involved a lot of manual error hunting and ensuring nothing was missing or leftover when done.

Beside the technical problems there is also the problem that the boundaries of the built-in packages are not well defined and a moving target.  There is a list of built-ins defined inside Emacs but that isn't sufficient.  I have gotten fixes to the list merged upstream, but getting it to the point were it would be sufficient for my needs would be to much work.

I ended up having to decide between these three options:
1. Investing huge amounts of time and stress (attempting to) getting the importer and categorization into a sane state.  Given that I haven't ever gotten any feedback what-so-ever on these repositories, and have failed to do so before, that didn't seem worth it.  Also there are other things related to the Emacsmirror that also need to be done that I consider much more important.
2. Keep the existing repositories but don't attempt to update them any more.  This goes against my attempt to get things cleaned up.  Also it wouldn't serve users who might very well assume that these repositories are more or less up-to-date.  That was never really the case but several Emacs releases out of date just ain't useful at all any more. (Also if someone wants to just use these packages s/he would just have to install a recent version of Emacs.  And to contribute to Emacs one would have the use the bzr repository or at least a git mirror of the full history anyway.)
3. Nuke repositories and have the pain end that maintaining this (purely) has caused me once and for all.  I should have announced that move.  I didn't because to some extend it was a rather spontaneous and emotional decision.  I had considered doing so before; but after another failed attempt to improve things I just had to be make the move and be done with it.  I had to do it before I would reconsider.

So I was aware this might cause some people a little pain but nothing compared to the stress trying to maintain this has caused me.  So again I am really sorry for the inconvenience this has caused but I do not regret having done it, just that I did not announce it.

Essentially I had to quit (the experiment of) extracting built-in packages so that I could again bring up the energy to continue maintaining the Emacsmirror and improve upon it's current state.

  Sincerely,
  Jonas

**Comment by vemv** [comment]
My god, what an answer! Now I feel sorry. I certainly was discussing a problem domain I knew very little about.

As you point out (and found on my own immediately after issuing this report), cua-base is in principle built-in into emacs. For some diabolic reason though, cua-base just wasn't there on some older Emacs installations of mine.

Perhaps you are familiar with that sort of problem. It is not affecting me anymore, anyway.

Keep up the good work, and may everything go well.

Victor

**Comment by tarsius** [comment]
Np :-)
